name: "Check outdate pods and create issue"
description: "Check for outdated pods and create issue in GitHub with the provided title (and other parameters) if it doesn't exist"

inputs:
  outdated-pod-name:
    description: "Enter the pod name for which outdated pods need to be searched" # Only one pod will be checked
    required: true
  directory:
    description: "Enter the directory where Podfile is located"
    required: true
  title: 
    description: "Title of the issue"
  body:
    description: "Description of the issue" # Leave it blank for predefined update message
  assignee: 
    description: "Assignee who'll be assigned for the isuue"
  labels:
    description: "The label for an issue that would be assigned while creating issue"
  color:
    description: "Colors for the label"
    default: FBCA04
  
outputs:
  issue-url: # id of output
    description: "The issue of the url if it is created or already exists"
    value: ${{ steps.set-output-variables.outputs.issue_url }}
  has-outdated-pod: # id of output
    description: "Outdated pod (which is given as input: outdated-pod-name) present"
    value: ${{ steps.set-output-variables.outputs.booleanValue }}

runs:
  using: "composite"
  steps:
    - name: Run shell script
      id: "set-output-variables"
      env:
        ISSUE_URL: ${{ env.ISSUE_URL }}
        HAS_OUTDATED_PODS: ${{ env.HAS_OUTDATED_PODS }}
      run: |
        chmod 0755 ${{ github.action_path }}/scripts/multiple_outdatedpod.sh
        source "${{ github.action_path }}/scripts/multiple_outdatedpod.sh" "${{ inputs.outdated-pod-name }}" "${{ inputs.directory }}" "${{ inputs.title }}" "${{ inputs.assignee }}" "${{ inputs.body }}" "${{ inputs.labels }}" "${{ inputs.color }}"
      
        echo "issue_url=$ISSUE_URL" >> $GITHUB_OUTPUT
        echo "booleanValue=$HAS_OUTDATED_PODS" >> $GITHUB_OUTPUT
        
      shell: sh
